# Generated by Django 2.1.2 on 2018-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfSnkrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='size',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
